<Project Sdk="Microsoft.NET.Sdk">

  <Import Project=".\..\..\CommonAssemblyInfo.props" />

  <PropertyGroup>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <!-- Create the configuration to buid various versions of Revit -->
    <Configurations>Debug;2025;2024;2023;2022;2021;2020;2019;2026;2027</Configurations>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>x64</Platforms>
    <NuGetAudit>false</NuGetAudit>
    <BuildInParallel>false</BuildInParallel>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>


  <!-- If the configuration is a Revit version,
    we use this configuration as a variable 
    for the rest of the csproj -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <RevitVersion>$(Configuration)</RevitVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <!-- We can only debug just ONE addin version.
         Instead of building all versions above,
         we just put ONE version below and switch to 'Debug' configuration
      -->
    <RevitVersion>2023</RevitVersion>
    <StartAction>Program</StartAction>
    <StartProgram>$(ProgramW6432)\Autodesk\Revit 2023\Revit.exe</StartProgram>
  </PropertyGroup>

  <Choose>
    <When Condition=" '$(RevitVersion)'=='2027'">
      <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition=" ('$(RevitVersion)'=='2025'  Or '$(RevitVersion)'=='2026')">
      <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <!-- Release -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <Optimize>true</Optimize>
    <OutputPath>bin\$(RevitVersion)\</OutputPath>
    <DefineConstants>REVIT$(RevitVersion)</DefineConstants>
    <NoWarn>MSB3052</NoWarn>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <!-- Debug -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;REVIT$(RevitVersion)</DefineConstants>
    <DebugType>Full</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <RevitNugetVersion>$(RevitVersion).*</RevitNugetVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Get the RevitAPI.dll, RevitAPIUI.dll, AdWindows.dll and UIFramework.dll -->
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitNugetVersion)" IncludeAssets="build; compile" PrivateAssets="All" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Resources\align-bottom-large.png" />
    <EmbeddedResource Include="Resources\align-bottom-small.png" />
    <EmbeddedResource Include="Resources\align-center-large.png" />
    <EmbeddedResource Include="Resources\align-center-small.png" />
    <EmbeddedResource Include="Resources\align-icon-grey-background.png" />
    <EmbeddedResource Include="Resources\align-icon-large.png" />
    <EmbeddedResource Include="Resources\align-icon-small.png" />
    <EmbeddedResource Include="Resources\align-left-large.png" />
    <EmbeddedResource Include="Resources\align-left-small.png" />
    <EmbeddedResource Include="Resources\align-middle-large.png" />
    <EmbeddedResource Include="Resources\align-middle-small.png" />
    <EmbeddedResource Include="Resources\align-right-large.png" />
    <EmbeddedResource Include="Resources\align-right-small.png" />
    <EmbeddedResource Include="Resources\align-top-large.png" />
    <EmbeddedResource Include="Resources\align-top-small.png" />
    <EmbeddedResource Include="Resources\arrange-large.png" />
    <EmbeddedResource Include="Resources\arrange-small.png" />
    <EmbeddedResource Include="Resources\distribute-horizontally-large.png" />
    <EmbeddedResource Include="Resources\distribute-horizontally-small.png" />
    <EmbeddedResource Include="Resources\distribute-vertically-large.png" />
    <EmbeddedResource Include="Resources\distribute-vertically-small.png" />
    <EmbeddedResource Include="Resources\untangle-horizontally-large.png" />
    <EmbeddedResource Include="Resources\untangle-horizontally-small.png" />
    <EmbeddedResource Include="Resources\untangle-vertically-large.png" />
    <EmbeddedResource Include="Resources\untangle-vertically-small.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer (1).cs" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Message Text="### AfterBuild ###" Importance="high" />
    <Exec Command="powershell -ExecutionPolicy Unrestricted $(ProjectDir)PostBuild.ps1 -RevitVersion $(RevitVersion) -TargetName $(TargetName) -ProjectDir $(ProjectDir) -TargetPath $(TargetPath) -TargetDir $(TargetDir) -Configuration $(Configuration)" />
  </Target>
</Project>